INSERT INTO user VALUES ('19001', 'yasuda', 'System', CURRENT_TIMESTAMP);
INSERT INTO user VALUES ('19002', 'takano', 'Sales', CURRENT_TIMESTAMP);
INSERT INTO user VALUES ('19003', 'imai', 'Finance', CURRENT_TIMESTAMP);